name: Device and Machine Package Validation

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  validate-device-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Setup LLGO
        uses: ./.github/actions/setup-llgo
        with:
          commit-hash: 8959c83397617dacb18a8de54c3a738303b66141
      - name: Run Device Package Validation
        run: |
          ./.github/scripts/validate_device_packages.sh device

  validate-machine-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Setup LLGO
        uses: ./.github/actions/setup-llgo
        with:
          commit-hash: 8959c83397617dacb18a8de54c3a738303b66141
      - name: Run Machine Package Validation
        run: |
          ./.github/scripts/validate_embed_packages.sh machine
